import csv

output_path = "/workspace/TSMC_Phoenix_vs_Taiwan_Fab_Costs.csv"

headers = [
    "Cost Category",
    "Phoenix, AZ (USA)",
    "Taipei / Hsinchu (Taiwan)",
    "Delta (AZ vs TW)",
    "Notes",
    "Sources",
]

rows = [
    ["", "", "", "", "", ""],
    ["═══ ELECTRICITY ═══", "", "", "", "", ""],
    [
        "Industrial Electricity Rate",
        "~$0.079/kWh",
        "~$0.136/kWh (NT$4.29/kWh after Oct 2024 hike)",
        "AZ ~42% cheaper",
        "AZ rate is Phoenix industrial avg. Taiwan rate is post-Oct 2024 industrial rate after 12.5% increase.",
        "EIA / Electricity Local; Taipei Times Oct 2024; TrendForce Mar 2024",
    ],
    [
        "Electricity per Wafer (est.)",
        "~$3.20/wafer (40.5 kWh x $0.079)",
        "~$5.51/wafer (40.5 kWh x $0.136)",
        "AZ ~42% cheaper",
        "Per-wafer electricity is 40.5 kWh (TSMC 2023 data for 3nm-class).",
        "WCCFTech (TSMC 2023 ESG data); rate sources above",
    ],
    [
        "Grid Reliability / Renewables",
        "APS/SRP grid; solar potential high; ~12% renewable",
        "Taipower; ~8-10% renewable; green power deficit concern",
        "Comparable",
        "Both regions face grid strain from fab expansion.",
        "Reuters Jun 2024; Stand.earth Feb 2024",
    ],
    ["", "", "", "", "", ""],
    ["═══ WATER ═══", "", "", "", "", ""],
    [
        "Industrial Water Rate",
        "~$8.25/1,000 gal (~$2.18/m3)",
        "~$0.37/m3 (NT$11-14/m3 industrial est.)",
        "AZ ~5-6x more expensive",
        "Phoenix uses tiered seasonal pricing. Taiwan water unchanged for 31 years.",
        "City of Phoenix Water Rates Mar 2025; Focus Taiwan Jan 2024; Taipei Times Mar 2025",
    ],
    [
        "Water Consumption per Wafer",
        "~3,000-5,000 liters/wafer start (leading edge)",
        "~3,000-5,000 liters/wafer start (leading edge)",
        "Same",
        "TSMC Taiwan achieves ~90% recycling; AZ currently ~65%, targeting 85-90% by 2028.",
        "Energy Solutions 2026; AZ Central Jun 2024; AZ Central Aug 2025",
    ],
    [
        "Water Cost per Wafer (est.)",
        "~$6.54-$10.90/wafer",
        "~$1.11-$1.85/wafer",
        "AZ ~5-6x more expensive",
        "Based on 3,000-5,000 L/wafer x local rate. Water is <0.1% of total wafer cost.",
        "Calculated from rates and consumption above",
    ],
    [
        "Total Fab Water Usage",
        "~4.75M gallons/day at full capacity",
        "~10-20M gallons/day per leading-edge fab",
        "Similar scale",
        "Hsinchu faces water supply challenges; MOEA targeting no industrial cuts before Jun 2026.",
        "AZ Central Jun 2024; Digitimes Mar 2026; Business Insider Jul 2024",
    ],
    ["", "", "", "", "", ""],
    ["═══ NATURAL GAS ═══", "", "", "", "", ""],
    [
        "Industrial Natural Gas Rate",
        "~$5.33/MCF (~$0.19/m3)",
        "~$0.35/m3 (NT$11.35/m3 NG(1) industrial Aug 2024)",
        "AZ ~46% cheaper",
        "AZ ranked #1 nationally for affordable natural gas.",
        "EIA 2024; CPC Corporation Taiwan Aug 2024",
    ],
    ["", "", "", "", "", ""],
    ["═══ LABOR ═══", "", "", "", "", ""],
    [
        "Process Engineer Salary (median)",
        "~$118,000/yr ($96K-$147K total comp)",
        "~$72,000/yr (NT$2.32M-2.62M median)",
        "AZ ~64% higher",
        "US wages ~3x Taiwan avg, but engineer gap smaller due to TSMC Taiwan's above-market pay. Labor <2% of wafer cost.",
        "Glassdoor (TSMC Phoenix); Levels.fyi (TSMC Taiwan); TechInsights Mar 2025",
    ],
    [
        "Technician/Operator Salary",
        "~$45,000-$65,000/yr",
        "~$18,000-$30,000/yr (NT$600K-1M)",
        "AZ ~2-3x higher",
        "Technician roles show larger gap. AZ requires significant training investment.",
        "Industry estimates; TSMC Taiwan salary data",
    ],
    [
        "Labor as % of Wafer Cost",
        "<2%",
        "<2%",
        "Negligible impact",
        "Modern fabs highly automated. Despite ~3x wage differential, labor impact on per-wafer cost is minimal.",
        "TechInsights Mar 2025",
    ],
    ["", "", "", "", "", ""],
    ["═══ EQUIPMENT & DEPRECIATION ═══", "", "", "", "", ""],
    [
        "Equipment Cost (% of wafer cost)",
        ">67% of total wafer cost",
        ">67% of total wafer cost",
        "Same",
        "Equipment from ASML, Applied Materials, KLA, Lam Research, Tokyo Electron priced same globally.",
        "TechInsights Mar 2025; SemiWiki; TechPowerUp Mar 2025",
    ],
    [
        "EUV Lithography System",
        "~$200-350M per tool",
        "~$200-350M per tool",
        "Same",
        "ASML EUV/High-NA EUV globally priced. Lithography ~25% of total wafer fabrication cost.",
        "ASML pricing data; costdata.de",
    ],
    [
        "Fab Construction Cost",
        "~$20B per fab (4-5x Taiwan)",
        "~$4-5B per equivalent fab",
        "AZ 4-5x higher (capex)",
        "Construction premium from US labor, regulatory/permitting, greenfield complexity. Total AZ commitment: $65B for 3 fabs.",
        "Wikipedia (TSMC Arizona); TechOvedas; BlackRidge Research",
    ],
    ["", "", "", "", "", ""],
    ["═══ MATERIALS & CHEMICALS ═══", "", "", "", "", ""],
    [
        "Process Chemicals & Gases",
        "Higher (import from Asia + US sourcing)",
        "Lower (proximity to Asian supply chain)",
        "AZ ~10-15% higher",
        "Modern fab uses 50-100 gas species, 30-60 liquid chemical precursors.",
        "AppIT Software; Silicon Analysts 2026; costdata.de",
    ],
    [
        "Silicon Wafer Blanks (300mm)",
        "~$130-$150/wafer",
        "~$130-$150/wafer",
        "Same",
        "Raw 300mm silicon wafer blanks globally commoditized.",
        "Industry pricing data; Silicon Analysts 2026",
    ],
    [
        "Photomask Sets",
        "~$5-15M per set (advanced nodes)",
        "~$5-15M per set (advanced nodes)",
        "Same",
        "Photomask costs are node-dependent, not location-dependent.",
        "costdata.de; industry estimates",
    ],
    ["", "", "", "", "", ""],
    ["═══ TAXES & GOVERNMENT INCENTIVES ═══", "", "", "", "", ""],
    [
        "Corporate Income Tax Rate",
        "21% federal + 6.968% AZ = ~28% combined",
        "20% + 5% surtax on undistributed earnings",
        "AZ ~3-8% higher nominal",
        "Effective rates differ due to credits/deductions. Both offer substantial semiconductor incentives.",
        "Tax Foundation 2024; Deloitte Taiwan Highlights 2024",
    ],
    [
        "Semiconductor Tax Credits (R&D)",
        "Federal: 25% AMTC or 20% regular R&D credit; AZ: up to $30K/job",
        "25% R&D deduction (>=NT$6B, 6% intensity); 5% equipment deduction (>=NT$10B)",
        "Both generous",
        "Taiwan CHIPS Act (Feb 2024) offers historic tax breaks. AZ: up to $125M/yr through 2030.",
        "TrendForce Jan 2024; AZ Commerce Authority; US CHIPS Act",
    ],
    [
        "Federal/National Subsidies",
        "$6.6B direct CHIPS Act + $5B loans",
        "Indirect via tax incentives; NT$350B+ various programs",
        "AZ larger direct grants",
        "TSMC AZ: $6.6B direct + $5B loans. Conditions: 5-yr buyback restrictions, upside sharing.",
        "Reuters Nov 2024; AZ Commerce Authority Apr 2024; NIST",
    ],
    [
        "Property Tax Rate",
        "~0.44-0.47% (Maricopa County)",
        "~0.2-1% (Hsinchu; science park concessions)",
        "AZ slightly higher",
        "Maricopa County rate below AZ avg (0.55%) and national avg (0.91%).",
        "PropertyTaxByState 2024; Hsinchu Local Tax Bureau",
    ],
    ["", "", "", "", "", ""],
    ["═══ LAND & REAL ESTATE ═══", "", "", "", "", ""],
    [
        "Industrial Land Cost",
        "~$24,000/acre (2024 auction near TSMC)",
        "Hsinchu Science Park: government-subsidized lease rates",
        "Variable",
        "AZ land at state auction. TSMC AZ site: 1,129 acres. Taiwan science parks: subsidized long-term leases.",
        "AZ Central May 2024; InvestTaiwan",
    ],
    ["", "", "", "", "", ""],
    ["═══ LOGISTICS & SUPPLY CHAIN ═══", "", "", "", "", ""],
    [
        "Wafer Post-Processing Logistics",
        "Ship back to Taiwan for dicing/test/packaging",
        "On-site or nearby OSAT facilities",
        "AZ disadvantage",
        "Current AZ production returns wafers to Taiwan for back-end. Adds cost and 2-4 weeks transit.",
        "TechInsights Mar 2025; TechPowerUp Mar 2025",
    ],
    [
        "Supply Chain Proximity",
        "Limited local ecosystem; most materials imported",
        "Mature local ecosystem; dense supplier network",
        "TW advantage",
        "Taiwan has decades of supply chain density. AZ ecosystem nascent but growing.",
        "Industry analysis; AZ Central Mar 2026",
    ],
    ["", "", "", "", "", ""],
    ["═══ DICING, PACKAGING & BACKEND COSTS (AZ-MADE CHIPS) ═══", "", "", "", "", ""],
    [
        "Backend Process Flow (AZ chips)",
        "Wafers air-freighted to Taiwan for dicing/test/packaging",
        "Dicing/test/packaging done on-site or nearby OSAT",
        "AZ adds logistics loop",
        "AZ wafers fly back to Taiwan via Eva Air for all backend. Adds ~2-4 weeks transit time.",
        "SemiWiki; TechPowerUp Feb 2025; inkl.com Mar 2025",
    ],
    [
        "Air Freight Cost (AZ->TW)",
        "Est. ~$50-$150/wafer (specialized handling)",
        "N/A (no shipping needed)",
        "Added AZ cost",
        "300mm wafers need specialized FOUPs, temp/vibration control, insurance. Air freight 1-5 days.",
        "Wafer World; FreightAmigo; industry estimates",
    ],
    [
        "Wafer Dicing",
        "Done in Taiwan (same cost + freight)",
        "~$30-$80/wafer (blade or laser, 300mm)",
        "AZ adds freight overhead",
        "Laser dicing >42% market share for advanced nodes. Global dicing market: $614M (2024).",
        "Astute Analytica; Han's Laser; industry estimates",
    ],
    [
        "Wafer Probe / Wafer-Level Test",
        "Done in Taiwan (same cost)",
        "~$100-$300/wafer (varies by complexity)",
        "Same (done in TW)",
        "Probe testing IDs good dies before packaging. Test equip ~8% of fab equipment spend.",
        "SemiconductorInsight; MDPI Electronics",
    ],
    [
        "Packaging - Standard (FC-BGA)",
        "Done in Taiwan; ~$8/unit",
        "~$8/unit",
        "Same",
        "Flip-chip BGA standard for most logic chips. Set by OSAT (ASE/SPIL/Amkor).",
        "Silicon Analysts 2026",
    ],
    [
        "Packaging - InFO (Fan-Out WLP)",
        "Done in Taiwan; ~$15/unit",
        "~$15/unit",
        "Same",
        "TSMC InFO for Apple A/M-series, MediaTek. Revenue >$3.5B/yr.",
        "Silicon Analysts 2026; SemiconductorX; TechTicker",
    ],
    [
        "Packaging - CoWoS-S (2.5D)",
        "Done in Taiwan; ~$70/unit",
        "~$70/unit",
        "Same",
        "Dominant for AI/HPC (H100, MI300). Demand exceeds supply 40-50%, lead times 40-52 wks. Prices +20%.",
        "Silicon Analysts 2026; smbom.com; Morgan Stanley",
    ],
    [
        "Packaging - CoWoS-L (large interposer)",
        "Done in Taiwan; ~$84-$98/unit",
        "~$84-$98/unit",
        "Same",
        "CoWoS-L for NVIDIA B200 Blackwell. 20-40% more than CoWoS-S.",
        "Silicon Analysts packaging calc; NVIDIA B200 breakdown",
    ],
    [
        "Packaging - SoIC (3D Stacking)",
        "Done in Taiwan; ~$120/unit",
        "~$120/unit",
        "Same",
        "Highest-density 3D stacking. Lowest volume, highest cost.",
        "Silicon Analysts 2026",
    ],
    [
        "Full Backend Cost (H100-class AI chip)",
        "~$750-$1,100/chip + AZ freight",
        "~$750-$1,100/chip",
        "AZ adds ~$50-$150 freight",
        "H100 SXM5 COGS ~$3,320; CoWoS-S ~$750. B200 COGS ~$6,400; CoWoS-L ~$1,100.",
        "Silicon Analysts (H100/B200 breakdown)",
    ],
    [
        "Backend as % of Total Chip Cost",
        "~10-20% (std); ~20-30% (AI/HPC with CoWoS)",
        "~10-20% (std); ~20-30% (AI/HPC with CoWoS)",
        "Same % (same providers)",
        "Backend share growing. OSAT price hikes 8-20%. Memory packaging surcharges +30%.",
        "SemiconductorX; Silicon Analysts",
    ],
    [
        "OSAT Price Trend",
        "8-20% price hikes (2025-2026)",
        "8-20% price hikes (2025-2026)",
        "Same",
        "ASE expects adv. packaging revenue to double in 2026. Near 90% utilization.",
        "Silicon Analysts; Digitimes Feb 2026",
    ],
    ["", "", "", "", "", ""],
    ["═══ GROSS MARGIN COMPARISON ═══", "", "", "", "", ""],
    [
        "TSMC Corporate Gross Margin (2025)",
        "59.9% FY; 62.3% Q4 2025",
        "59.9% FY; 62.3% Q4 2025",
        "N/A (consolidated)",
        "Up 3.8pp from 56.1% in 2024. Q4 beat guidance by 1.3pp. N3 scaling + FX + pricing.",
        "Finovian; MacroTrends; TSMC Q4 2025 results",
    ],
    [
        "TSMC Operating Margin (2025)",
        "50.8% FY; 54.0% Q4 2025",
        "50.8% FY; 54.0% Q4 2025",
        "N/A (consolidated)",
        "Up 5.1pp from 45.7% in 2024. Net income ~$55.4B, +51.7% YoY.",
        "Finovian; TSMC investor relations",
    ],
    [
        "Arizona Fab Estimated Gross Margin",
        "~8% (5nm production, est. 2025)",
        "~50-60% (mature Taiwan fabs)",
        "AZ ~42-52pp lower",
        "Low margin reflects new-fab depreciation, ramp-up, and all cultural efficiencies priced explicitly in US.",
        "White Hsu Blog (Feb 2026); mbi-deepdives.com",
    ],
    [
        "Arizona Fab Net Profit (2025)",
        "NT$161.4B (~$5.15B) profit",
        "N/A (not separately reported)",
        "First profitable year",
        "Swing from NT$142B loss in 2024. Gov't grants (25% of qualified investment) aided performance.",
        "BigGo Finance; TrendForce Mar 2026; AZ Tech Council",
    ],
    [
        "Arizona Margin Dilution Impact",
        "1-2% dilution to corporate margin (2025)",
        "N/A",
        "Manageable",
        "Overseas fabs dilute corporate GM 2-3% early, 3-4% at scale. 2025 revised to 1-2%.",
        "mbi-deepdives.com; BeyondSPX; Yahoo Finance",
    ],
    [
        "Wafer Price Premium (AZ vs TW)",
        "5-20% premium charged to customers",
        "Baseline pricing",
        "+5-20%",
        "AMD CEO Lisa Su confirmed. TSMC CEO: 'geographic flexibility' premium. Customers agreed.",
        "The Verge; Yahoo Finance; Taiwan News May 2025",
    ],
    [
        "Long-Term Margin Trajectory (AZ)",
        "Improving toward ~30-40% (3-5 yr consensus)",
        "Stable at ~50-60%",
        "Gap narrowing",
        "Improving via: lower depreciation, yields (92% N4P vs 88% Hsinchu), ecosystem maturity, scale.",
        "Digitimes; ainvest.com; analyst consensus",
    ],
    [
        "Key Margin Differentiator",
        "Cultural costs explicit (formal labor, compliance)",
        "Cultural efficiencies informal (unpaid OT, flexible roles)",
        "Structural",
        "Taiwan margins partly from 'invisible costs' - engineers returning w/o being called, blurred roles, etc.",
        "White Hsu Blog (Feb 2026)",
    ],
    ["", "", "", "", "", ""],
    ["═══ OVERALL WAFER PROCESSING COST ═══", "", "", "", "", ""],
    [
        "Total Wafer Processing Cost (300mm N4/N3)",
        "~$17,000-$22,000/wafer",
        "~$15,500-$20,000/wafer",
        "AZ ~10% higher overall",
        "Per TechInsights Strategic Cost & Price Model. Equipment dominance (~67%+) equalizes locations.",
        "TechInsights Mar 2025; Silicon Analysts 2026; SemiWiki",
    ],
    [
        "Total Chip Cost incl. Backend (AI/HPC)",
        "~$3,500-$7,000/chip (wafer + backend + freight)",
        "~$3,300-$6,400/chip (wafer + backend)",
        "AZ ~5-10% higher all-in",
        "For H100/B200 class. Frontend +10% AZ; backend identical (done in TW); freight ~$50-150.",
        "Silicon Analysts; TechInsights; calculated",
    ],
    [
        "Operating Cost Premium (all-in)",
        "Baseline + ~10%",
        "Baseline",
        "+10%",
        "Final TechInsights assessment. Earlier 30-50%+ estimates were flawed. Equipment parity is decisive.",
        "TechInsights Mar 2025; TechPowerUp Feb & Mar 2025",
    ],
]

with open(output_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["TSMC Fab Operational Costs: Phoenix AZ vs. Taipei/Hsinchu Taiwan"])
    writer.writerow(["Data compiled from public sources (2024-2026). All USD conversions at ~NT$32.5 = US$1."])
    writer.writerow([])
    writer.writerow(headers)
    writer.writerows(rows)

print(f"CSV saved to {output_path}")

# ── Second CSV: Expansion Phases ──
phases_path = "/workspace/TSMC_Arizona_Expansion_Phases.csv"
phase_headers = [
    "Facility", "Process Node", "Status", "Announced",
    "Production Start", "Capacity (WPM)", "Key Details", "Sources",
]
phase_rows = [
    ["═══ FABRICATION PLANTS (6 FABS) ═══", "", "", "", "", "", "", ""],
    [
        "Fab 21 Phase 1", "N4P / N5 (4nm)", "OPERATIONAL", "May 2020",
        "Q4 2024 (HVM early 2025)", "10K->30K WPM (ramping)",
        "92% N4P yield (exceeds TW 88%). Producing Apple A16, S9, AMD Ryzen 9000, NVIDIA Blackwell. "
        "Apple 100M+ chips 2026. First profitable year 2025 ($5.15B). Amkor Peoria for some Apple packaging.",
        "Wikipedia; Tom's HW Jan 2025; AZ Central Feb 2026; TrendForce Feb 2025",
    ],
    [
        "Fab 21 Phase 2", "N3 (3nm)", "CONSTRUCTION COMPLETE / Tool install 2026", "Dec 2022",
        "H2 2027 (accelerated from 2028)", "~20K WPM (est.)",
        "Building done 2025. Equip move-in 2026, tool install Q3 2026. Timeline compressed from 6 to 4-5 quarters. "
        "Capacity already booked.",
        "TrendForce Mar 2026; Digitimes Dec 2025; theGPUTrade",
    ],
    [
        "Fab 21 Phase 3", "N2 / A16 (2nm / 1.6nm)", "UNDER CONSTRUCTION", "Apr 2024",
        "2029 (some reports: 2027 accelerated)", "TBD",
        "Broke ground Apr 2025. Nanosheet (GAA) transistors. A16 incl backside power delivery. "
        "Part of original $65B (3 fabs).",
        "Wikipedia; TechOvedas; Tom's HW Jul 2025; NIST",
    ],
    [
        "Fab 21 Phase 4", "TBD (likely N2/A16+)", "PLANNED", "Mar 2025",
        "~2030 (est.)", "TBD",
        "Part of additional $100B (3 more fabs). Fully booked before construction begins "
        "(Apple, NVIDIA, AMD, Broadcom, Qualcomm). Permits filed.",
        "Barchart; PCMag Mar 2025; Wikipedia",
    ],
    [
        "Fab 21 Phase 5", "TBD", "PLANNED", "Mar 2025", "TBD", "TBD",
        "Part of 6-fab gigafab. AZ will represent 30% of 2nm+ capacity at full buildout. "
        "CFO: expansion not done after $165B.",
        "CNBC Jan 2026; AZ Central Jul 2025; Wikipedia",
    ],
    [
        "Fab 21 Phase 6", "TBD", "PLANNED", "Mar 2025", "TBD", "TBD",
        "Final fab. ~900 additional acres acquired for total ~2,000-acre complex.",
        "Wikipedia; Wedbush Jan 2026; BlackRidge",
    ],
    ["", "", "", "", "", "", "", ""],
    ["═══ SUPPORTING FACILITIES ═══", "", "", "", "", "", "", ""],
    [
        "Adv. Packaging 1 (AP1)", "CoWoS / CoPoS / SoIC", "PLANNED", "2025",
        "Late 2029 / Early 2030", "N/A",
        "First US advanced packaging. Groundbreaking 2028. CoPoS pilot line 2026. "
        "Partnership with Amkor (Peoria AZ). Eliminates need to fly wafers back to TW.",
        "TechPowerUp Jul 2025; FinancialContent Jan 2026; Amkor Oct 2024",
    ],
    [
        "Adv. Packaging 2 (AP2)", "TBD", "PLANNED", "2025", "TBD", "N/A",
        "Second packaging facility. Early planning. Part of gigafab cluster.",
        "Wikipedia; InBusinessPHX; NIST",
    ],
    [
        "R&D Center", "N/A", "PLANNED", "2025", "TBD", "N/A",
        "Process development and yield optimization for US manufacturing.",
        "Wikipedia; PCMag Mar 2025; NIST",
    ],
    ["", "", "", "", "", "", "", ""],
    ["═══ KEY METRICS ═══", "", "", "", "", "", "", ""],
    ["Total Investment", "$165B (potentially $265B)", "", "", "", "", "", ""],
    ["Federal Subsidies", "$6.6B direct + $5B loans", "", "", "", "", "", ""],
    ["Site Area", "~2,000 acres", "", "", "", "", "", ""],
    ["Direct Mfg Jobs (full buildout)", "~6,000", "", "", "", "", "", ""],
    ["Current Employees (2024)", "~3,000", "", "", "", "", "", ""],
    ["Construction Jobs", "~20,000+", "", "", "", "", "", ""],
    ["Key Customers", "Apple (100M+ chips 2026), NVIDIA, AMD, Qualcomm, Broadcom", "", "", "", "", "", ""],
    ["AZ Share of Adv. Capacity", "30% of 2nm+ at full buildout", "", "", "", "", "", ""],
    ["N4P Yield Achievement", "92% (exceeds Taiwan's 88%)", "", "", "", "", "", ""],
    ["Build Time Compression", "~3 years (Fab 1) -> ~1.5-2 years (subsequent)", "", "", "", "", "", ""],
    ["2026 CapEx (Company-wide)", "$52-56B (+40% vs 2025)", "", "", "", "", "", ""],
    ["Halo Vista Development", "3,500-acre mixed-use adjacent to TSMC site", "", "", "", "", "", ""],
    ["Key Suppliers (On-site)", "Amkor (packaging); Linde (N2/O2/Ar); Air Liquide (H2/He/CO2)", "", "", "", "", "", ""],
]

with open(phases_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["TSMC Arizona Fab Expansion: Phase-by-Phase Status (as of Mar 2026)"])
    writer.writerow(["Total: $165B committed. 6 fabs + 2 advanced packaging + 1 R&D center on ~2,000 acres."])
    writer.writerow([])
    writer.writerow(phase_headers)
    writer.writerows(phase_rows)

print(f"Phases CSV saved to {phases_path}")
